# Generated by Django 3.2.7 on 2022-02-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsCategory',
            new_name='NewsCategories',
        ),
    ]
