# Generated by Django 3.2.7 on 2022-02-25 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_newscategory_newscategories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscategories',
            old_name='category',
            new_name='categories',
        ),
    ]
